<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Agreements</h2>

    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="ibox-content m-b-sm border-bottom">
        <div class="row">
            <div class="col-sm-2">
                <div class="form-group">
                    <label class="control-label" for="product_name">Agreement Number</label>
                    <input type="text" id="product_name" name="product_name" value="" placeholder="Agreement Number" class="form-control">
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label class="control-label" for="price">Brand</label>
                    <select id="price" name="brand" class="form-control">
                        <option>Select Brand</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label class="control-label" for="quantity">Customer</label>
                    <select id="price" name="brand" class="form-control">
                        <option>Select Customer</option>
                    </select>
                </div>
            </div>


            <div class="col-sm-2">
                <div class="form-group">
                    <label class="control-label" for="quantity">Supplier</label>
                    <select id="price" name="brand" class="form-control">
                        <option>Select Supplier</option>
                    </select>
                </div>
            </div>

            <div class="col-sm-2">
                <div class="form-group">
                    <label class="control-label" for="status">Status</label>
                    <select name="status" id="status" class="form-control">
                        <option value="1" selected="">Enabled</option>
                        <option value="0">Disabled</option>
                    </select>
                </div>
            </div>

            <div class="col-sm-1">
                <i style="font-size: 26px; margin-top: 32px;" class="fa fa-cloud-upload" data-toggle="modal" data-target="#myModal"></i>
            </div>


        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">

                    <ul class="pagination pull-right">
                        <li class="footable-page-arrow disabled">
                            <a data-page="first" href="#first">«</a>
                        </li>

                        <li class="footable-page-arrow disabled">
                            <a data-page="prev" href="#prev">‹</a>
                        </li>

                        <li class="footable-page active">
                            <a data-page="0" href="#">1</a>
                        </li>

                        <li class="footable-page">
                            <a data-page="1" href="#">2</a>
                        </li>

                        <li class="footable-page-arrow">
                            <a data-page="next" href="#next">›</a>
                        </li>

                        <li class="footable-page-arrow">
                            <a data-page="last" href="#last">»</a>
                        </li>
                    </ul>


                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Agreement Number</th>
                                <th>Brand</th>
                                <th>Customer</th>
                                <th>Supplier</th>
                                <th>Status</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr data-toggle="modal" data-target="#myModal2">
                                <td>
                                    #1
                                </td>
                                <td>
                                    Kitsound
                                </td>
                                <td>
                                    KON/1/10
                                </td>
                                <td>
                                    KON/1/10
                                </td>
                                <td class="client-status">
                                    <span class="label label-primary">Waiting Brand Approval</span>
                                </td>
                            </tr>

                            <tr data-toggle="modal" data-target="#myModal2">
                                <td>
                                    #2
                                </td>
                                <td>
                                    Kitsound
                                </td>
                                <td>
                                    KON/1/10
                                </td>
                                <td>
                                    KON/1/10
                                </td>
                                <td class="client-status">
                                    <span class="label label-danger">Abandoned</span>
                                </td>
                            </tr>

                        </tbody>

                    </table>

                </div>
            </div>
        </div>
    </div>
</div>



<!-- Import Modal -->
<div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Import</h4>
            </div>

            <div class="modal-body">
                <form id="importForm" style="">
                    <div style="display:none">
                        <input id="fileinput"  accept=".csv" type="file" name="somename">
                    </div>

                    <h2>You have 2 options...</h2>

                    <div class="row" style="margin-top: 20px;">
                        <h3>You can download the template</h3><br>
                        <button class="btn btn-success Upload" type="button"><i class="fa fa-download"></i>&nbsp;&nbsp;<span class="bold">Download Template</span></button>
                    </div>

                    <div class="row" style="margin-top: 20px">
                        <h2> or</h2>
                    </div>

                    <div class="row" style="margin-top: 20px">
                        <h3>You can upload a file for import</h3><br>
                        <button class="btn btn-success Upload" type="button"><i class="fa fa-upload"></i>&nbsp;&nbsp;<span class="bold">Upload</span></button>
                    </div>
                </form>

                <div class="results-container" style="display: none;">

                </div>
            </div>

        </div>
    </div>
</div>

<!-- View Agreement Modal -->
<div class="modal inmodal in" id="myModal2" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Agreement #1</h4>
            </div>

            <div class="modal-body" style="background-color: #FFF;">
                <p><strong>The claim is currently waiting brand approval</strong></p>
            </div>

            <ul class="list-unstyled project-files" style="margin-top: 16px; margin-left: 20px; font-size: 16px !important;">
                <li><i class="fa fa-file"></i> Supplier: KON/1/10</li>
                <li><i class="fa fa-file-picture-o"></i> Customer: KON/1/10</li>
                <li><i class="fa fa-stack-exchange"></i> Brand: Kitsound</li>
            </ul>


            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Accept</button>
                <button type="button" class="btn btn-danger">Reject</button>
                <button type="button" class="btn btn-danger">Abandon</button>
            </div>
        </div>
    </div>
</div>


<script>
    $ ('.Upload').on ('click', function ()
    {
        $ ('#fileinput').click ();
    });


    // Variable to store your files
    var files;

    // Add events
    $ ('#fileinput').on ('change', prepareUpload);

    // Grab the files and set them to our variable
    function prepareUpload (event)
    {
        showLoader ($ ('#importForm'));


        // Create a formdata object and add the files
        var formdata = new FormData ();

        files = event.target.files;

        if (files.length === 0)
        {
            alert ('No file uploaded');
            return false;
        }

        file = files[0];
        formdata.append ("Import", file);

        $.ajax ({
            url: '/blab/import/uploadFile',
            type: 'POST',
            data: formdata,
            cache: false,
            processData: false, // Don't process the files
            contentType: false, // Set content type to false as jQuery will tell the server its a query string request
            success: function (response)
            {

                try {

                    hideLoader ();

                    var objResponse = $.parseJSON (response);

                    if (objResponse.sucess == 0)
                    {
                        showErrorMessage (objResponse.data);
                    }
                    else
                    {
                        showSuccessMessage (objResponse.data);
                    }
                } catch (error) {
                    showErrorMessage (error);

                }
            },
            error: function (jqXHR, textStatus, errorThrown)
            {
                // STOP LOADING SPINNER
                hideLoader ();

                // Handle errors here
                showErrorMessage (errorThrown);


            }
        });
    }

    /**
     * 
     * @param {type} arrData
     * @returns {undefined}
     */
    function showErrorMessage (arrData)
    {
        $ ("#importForm").hide ();

        var HTML = '';


        $.each (arrData.errors, function (i, item)
        {
            HTML += '<div class="alert alert-danger">' +
                    item +
                    '</div>';
        });

        $ ('.results-container').html (HTML).show ();
    }

    /**
     * 
     * @param {type} arrData
     * @returns {undefined}
     */
    function showSuccessMessage (arrData)
    {
        $ ("#importForm").hide ();

        var HTML = '';


        $.each (arrData.results, function (i, item)
        {
            HTML += '<div class="alert alert-success">' +
                    item +
                    '</div>';
        });

        $ ('.results-container').html (HTML).show ();
    }

    function hideLoader ()
    {
        $ ('.loader').remove ();
    }

    /**
     * 
     * @param {type} element
     * @returns {undefined}
     */
    function showLoader (element)
    {
        element.append ('<img class="loader" src="/blab/public/img/loader.svg">');
    }

</script>
